consul:
  image: consul:0.7.5
  volumes:
    - ./config.json:/consul/config.json
    - ./ssl:/consul/ssl
#      - ./env/consul/ssl:/etc/consul.d/ssl
  ports:
    - 8300:8300     # Server RPC, Server Use Only
    - 8301:8301/tcp # Serf Gossip Protocol for LAN
    - 8301:8301/udp # Serf Gossip Protocol for LAN
    - 8400:8400     # CLI RPC
    - 8500:8500     # HTTP API & Web UI
    - 8501:8501     # HTTPS API & Web UI
    - 53:8600/tcp   # DNS Interface
    - 53:8600/udp   # DNS Interface
#    container_name: consul
  command: "agent -server -config-file=/consul/config.json -node consul -bootstrap-expect 1 -bind 0.0.0.0 -client 0.0.0.0 -ui" # -advertise 192.168.99.100"
